name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.4.11'
      SERVERPOD_PASSWORD_database: 'qAEQPKeiYyhAtCWE0Bms5BwiWLP8q9ke'
      SERVERPOD_PASSWORD_redis: 't7-GGU9IL0Z6Nipll-KSsfrtsr1A4wRn'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: pod_app_v1_server
        run: docker compose up --quiet-pull --build -d

      - name: Install dependencies
        run: flutter pub get

      - name: Install Serverpod CLI
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: pod_app_v1_server
        run: serverpod generate

      - name: Run tests
        working-directory: pod_app_v1_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: pod_app_v1_server
        run: docker compose down -v
